import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for ProfitPath — rules and guidelines for using our platform.",
  alternates: { canonical: "https://profitpath.online/terms" },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: March 16, 2026</p>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
        <section>
          <h2 className="text-xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
          <p>By accessing and using ProfitPath (profitpath.online), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">2. Description of Service</h2>
          <p>ProfitPath provides free AI-powered online tools for content creators, freelancers, and side hustlers. Our tools include income calculators, freelance rate calculators, YouTube content generators, AI prompt generators, and viral video planners.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">3. User Accounts</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You may use some tools without an account, subject to daily generation limits.</li>
            <li>Creating an account requires a valid email address or Google sign-in.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must provide accurate information when creating an account.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">4. Usage Limits</h2>
          <p>Free users are subject to daily generation limits. Additional generations can be unlocked by completing promotional tasks (watching recommendations). These limits may change at any time without notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">5. AI-Generated Content</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Content generated by our tools is created using AI (Google Gemini) and is provided as-is.</li>
            <li>You are free to use generated content for personal and commercial purposes.</li>
            <li>We do not guarantee the accuracy, originality, or suitability of AI-generated content.</li>
            <li>You are responsible for reviewing and editing generated content before publishing.</li>
            <li>We are not liable for any consequences arising from the use of AI-generated content.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">6. Prohibited Use</h2>
          <p>You may not:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Use our tools to generate harmful, illegal, or misleading content.</li>
            <li>Attempt to bypass generation limits through automated means or bots.</li>
            <li>Reverse-engineer, scrape, or abuse our APIs.</li>
            <li>Resell or redistribute our tools without permission.</li>
            <li>Use our service to spam or harass others.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">7. Affiliate Links & Promotions</h2>
          <p>ProfitPath displays affiliate links and promotional content. We may earn a commission when you interact with these promotions. This does not affect the cost to you. Promotional tasks are optional and are offered in exchange for additional generation credits.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">8. Intellectual Property</h2>
          <p>The ProfitPath platform, branding, and tools are owned by ProfitPath. Content you generate using our tools belongs to you. By saving content to our platform, you grant us permission to store it on your behalf.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">9. Limitation of Liability</h2>
          <p>ProfitPath is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from the use of our services, including but not limited to loss of data, revenue, or business opportunities.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">10. Termination</h2>
          <p>We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting us.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">11. Changes to Terms</h2>
          <p>We may update these Terms of Service at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">12. Third-Party Applications</h2>
          <p>ProfitPath operates and manages additional products and services, including but not limited to <strong>INZ Gaming</strong> (social media automation for gaming content). These products are operated under the same entity and are subject to these Terms of Service. By using any product or service operated by ProfitPath, you agree to these terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900">13. Contact</h2>
          <p>For questions about these Terms, contact us at <strong>support@profitpath.online</strong>.</p>
        </section>
      </div>
    </div>
  );
}
